### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Surendrajat** [otakuhqz/Omega#10]
The app crashed while I was using the phone.

## Description
Got a random pupup saying crash and restart app. Attached the stacktrace.

## Expected Behavior
Just keep running

## Actual Behavior
Crash

## Steps to Reproduce
Not sure

## Device and OS

* Device: Oppo K3 (CPH1955)
* Android version: 10
* Launcher version: 0.4.0
* Rom: ColorOS 7.1 stock

## Stacktrace

```
Build version: 0.4.0 
Current date: 2020-09-18 21:20:12 
Device: OPPO CPH1955 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
 at java.util.ArrayList.get(ArrayList.java:437)
 at com.android.launcher3.allapps.AllAppsStore.notifyUpdate(AllAppsStore.java:109)
 at com.android.launcher3.allapps.AllAppsStore.setApps(AllAppsStore.java:72)
 at com.android.launcher3.Launcher.bindAllApplications(Launcher.java:2405)
 at com.android.launcher3.model.BaseModelUpdateTask.lambda$bindApplicationsIfNeeded$5(BaseModelUpdateTask.java:125)
 at com.android.launcher3.model.-$$Lambda$BaseModelUpdateTask$ZKfpicMFanma9Of4-Ka4QkldVhU.execute(Unknown Source:2)
 at com.android.launcher3.model.BaseModelUpdateTask.lambda$scheduleCallbackTask$0$BaseModelUpdateTask(BaseModelUpdateTask.java:85)
 at com.android.launcher3.model.-$$Lambda$BaseModelUpdateTask$ATJWNkQbyIlBKEmpIGibYaAzgBk.run(Unknown Source:6)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:238)
 at android.app.ActivityThread.main(ActivityThread.java:7798)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)```

**Comment by otakuhqz** [comment]
fixed in commit [cd1c155](https://github.com/otakuhqz/Omega/commit/cd1c155db0daa74ed194844e2376ae5032ff667c)
