### ISSUE TITLE
Desktop mode crashes constantly

### ISSUE THREAD

**Issue by J4gQBqqR** [otakuhqz/Omega#107]
The new desktop mode 5a8a9931d83ae8749d2749dfecaeb46bb88f6cd3 does not seem to work. 

## Description
In the system->developer options, the desktop mode and freeform window options are enabled.

## Expected Behavior
When connecting to second display, I am expecting a taskbar to appear.

## Actual Behavior
Omega Launcher keeps crashing. The second display keeps flashing between wall paper and back screen.

## Device and OS

* Device: Oneplus 7 pro
* Android version: 11
* Launcher version: 8.1
* Rom: LineageOS 18.1

**Comment by J4gQBqqR** [comment]
`Build version: 0.8.1 
Build date: 1981-01-01 01:01:02 
Current date: 2021-08-19 17:23:30 
Device: OnePlus GM1917 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
android.view.InflateException: Binary XML file line #43 in com.saggitt.omega:layout/secondary_launcher: Binary XML file line #43 in com.saggitt.omega:layout/secondary_launcher: Error inflating class com.android.launcher3.allapps.AllAppsContainerView
Caused by: android.view.InflateException: Binary XML file line #43 in com.saggitt.omega:layout/secondary_launcher: Error inflating class com.android.launcher3.allapps.AllAppsContainerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:455)
	at android.app.Activity.setContentView(Activity.java:3468)
	at com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher.initUi(SecondaryDisplayLauncher.java:103)
	at com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher.onAttachedToWindow(SecondaryDisplayLauncher.java:85)
	at com.android.internal.policy.DecorView.onAttachedToWindow(DecorView.java:1712)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2435)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ClassCastException: com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher cannot be cast to com.android.launcher3.Launcher
	at com.android.launcher3.Launcher.getLauncher(Launcher.java:361)
	at com.android.launcher3.allapps.AllAppsContainerView.<init>(AllAppsContainerView.java:125)
	at com.android.launcher3.allapps.AllAppsContainerView.<init>(AllAppsContainerView.java:119)
	... 31 more
`

**Comment by KrisadaFantasy** [comment]
By the way, is there any option to manually enable Desktop Mode? I use [scrcpy](https://github.com/genymobile/scrcpy/) to project my phone to my PC along with Taskbar app. Would like to try native solution from Omega itself.
