### ISSUE TITLE
[0.8.1] crash when open a folder in drawer

### ISSUE THREAD

**Issue by Loader009** [otakuhqz/Omega#109]
## Description

crash when I open a folder within the drawer (only drawer, dock works fine)
Happens since the latest update.

## Expected Behavior

Folder should open and show all the apps inside

## Actual Behavior

Launcher crashes

## Steps to Reproduce

1. have folder in drawer
2. click on folder in drawer
3. crash

## Device and OS

* Device: FxTec Pro¹
* Android version: 9
* Launcher version: 0.8.1
* Rom: LineageOS 16.0

## Stack Trace

```
Build version: 0.8.1 
Build date: 1981-01-01 01:01:02 
Current date: 2021-08-21 14:13:31 
Device: Unknown 
OS version: Android 9 (SDK 28) 
 
Stack trace:  
java.lang.IllegalArgumentException: Cannot set 'scaleX' to Infinity, the value must be <= 3.4028235E38
 at android.view.View.sanitizeFloatPropertyValue(View.java:15417)
 at android.view.View.sanitizeFloatPropertyValue(View.java:15399)
 at android.view.View.setScaleX(View.java:14788)
 at com.android.launcher3.folder.FolderAnimationManager.getAnimator(FolderAnimationManager.java:142)
 at com.android.launcher3.folder.Folder.animateOpen(Folder.java:644)
 at com.android.launcher3.folder.Folder.animateOpen(Folder.java:595)
 at com.android.launcher3.folder.Folder.animateOpen(Folder.java:586)
 at com.android.launcher3.touch.ItemClickHandler.onClickFolderIcon(ItemClickHandler.java:145)
 at com.android.launcher3.touch.ItemClickHandler.onClick(ItemClickHandler.java:104)
 at com.android.launcher3.touch.ItemClickHandler.lambda$getInstance$0(ItemClickHandler.java:83)
 at com.android.launcher3.touch.ItemClickHandler$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
 at android.view.View.performClick(View.java:6597)
 at android.view.View.performClickInternal(View.java:6574)
 at android.view.View.access$3100(View.java:778)
 at android.view.View$PerformClick.run(View.java:25906)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6718)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Aviortheking** [comment]
Also the icons are not displayed 
![Screenshot_20210822-113113.jpg](https://user-images.githubusercontent.com/15822031/130350164-225fb58b-2850-446b-9148-d20ad4494220.jpg)

**Comment by Loader009** [comment]
@Aviortheking 
That's another issue and happens randomly on the old version as well.

**Comment by Aviortheking** [comment]
Oh ok, I thought it was related since it crashed on these folders xd

**Comment by Loader009** [comment]
@Aviortheking 
please check out issue #110
