### ISSUE TITLE
Crash on open v0.4.0 (build 32)

### ISSUE THREAD

**Issue by bushrang3r** [otakuhqz/Omega#12]
App crashes on start

## Expected Behavior

App should start

## Actual Behavior

Homescreen icons of other launcher disappear and only background wallpaper is displayed. Tapping home button returns to usual homescreen of other launcher.

## Steps to Reproduce

1. Install apk
2. Tap on icon
3. > see actual behavior

## Device and OS

* Device: LG G6 (h870)
* Android version: 10
* Launcher version: v.0.4.0
* Rom: Havoc OS

## Logcat

```
09-22 07:31:02.595 I/ActivityTaskManager(1081): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.saggitt.omega/.OmegaLauncher bnds=[864,402][1152,692]} from uid 10256
09-22 07:31:02.693 I/ActivityManager(1081): Start proc 6557:com.saggitt.omega/u0a264 for top-activity {com.saggitt.omega/com.saggitt.omega.OmegaLauncher}
09-22 07:31:02.887 I/FA      (6557):   adb shell setprop debug.firebase.analytics.app com.saggitt.omega
09-22 07:31:03.039 V/chatty  (6557): uid=10264(com.saggitt.omega) identical 7 lines
09-22 07:31:03.042 V/chatty  (6557): uid=10264(com.saggitt.omega) identical 4 lines
09-22 07:31:03.044 W/System.err(6557): 	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.java:84)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.java:84)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackManager$onPacksUpdated$1.invoke(IconPackManager.kt:324)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackManager$onPacksUpdated$1.invoke(IconPackManager.kt:52)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.util.OmegaUtilsKt.runOnThread(OmegaUtils.kt:161)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.util.OmegaUtilsKt.runOnMainThread(OmegaUtils.kt:156)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackManager.onPacksUpdated(IconPackManager.kt:200)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackList$onPackListUpdated$1.run(IconPackList.kt:69)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackList.onPackListUpdated(IconPackList.kt:45)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackList.setPackList(IconPackList.kt:95)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackList.reloadPacks(IconPackList.kt:91)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackList.<init>(IconPackList.kt:41)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackManager.<init>(IconPackManager.kt:65)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.iconpack.IconPackManager$Companion.getInstance(IconPackManager.kt:298)
09-22 07:31:03.084 E/Overrides(6557): 	at com.saggitt.omega.icons.CustomDrawableFactory.<init>(CustomDrawableFactory.kt:37)
09-22 07:31:03.086 W/System.err(6557): 	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.java:84)
09-22 07:31:03.184 W/ActivityManager(1081): Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.saggitt.omega:10264?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
09-22 07:31:03.203 E/AndroidRuntime(6557): Process: com.saggitt.omega, PID: 6557
09-22 07:31:03.215 W/ActivityManager(1081): Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.saggitt.omega:10264?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
09-22 07:31:03.276 V/chatty  (6557): uid=10264(com.saggitt.omega) identical 3 lines
09-22 07:31:03.343 D/AppLockService(3232): Window state changed: com.saggitt.omega
09-22 07:31:03.378 V/chatty  (6557): uid=10264(com.saggitt.omega) identical 2 lines
09-22 07:31:03.422 I/ActivityTaskManager(1081): Displayed com.saggitt.omega/.OmegaLauncher: +809ms
09-22 07:31:03.436 V/chatty  (6557): uid=10264(com.saggitt.omega) identical 1 line

```

**Comment by otakuhqz** [comment]
do you have the google app installed?

**Comment by bushrang3r** [comment]
Yes, it is installed. It's a custom version.

https://forum.xda-developers.com/android/software/gapps-flamegapps-android-t4020917
