### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by D3ZOXY** [otakuhqz/Omega#128]
Build version: 0.8.2 
Build date: 1981-01-01 01:01:02 
Current date: 2021-10-10 15:01:23 
Device: Realme RMX1991 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.AbstractMethodError: abstract method "void android.view.IRemoteAnimationRunner.onAnimationStart(android.view.RemoteAnimationTarget[], android.view.IRemoteAnimationFinishedCallback)"
	at android.view.IRemoteAnimationRunner$Stub.onTransact(IRemoteAnimationRunner.java:106)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

**Comment by otakuhqz** [comment]
need more information to work on it
