### ISSUE TITLE
Crashes when clicking "Get More" icon packs.

### ISSUE THREAD

**Issue by 5lttrz** [otakuhqz/Omega#145]
## Description

Crashes when trying to add custom icon packs.

## Expected Behavior

It should let us add custom icon packs

## Actual Behavior

Crashes

## Steps to Reproduce

1.  Open Omega Laucher Settings
2. Go to Themes > Icon Packs
3. Click on "Get More"
4. Crashes

## Device and OS

* Device: Samsung Galaxy M21
* Android version: Android 11
* Launcher version: 0.8.1 IzzyOnDroid Repo
* Rom: OneUI

## Logcat

```
Build version: 0.8.1 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-31 21:09:00 
Device: Samsung SM-M215F 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://search?c=apps&q=Icon pack flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2080)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5377)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:588)
	at android.app.Activity.startActivityForResult(Activity.java:5335)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at android.app.Activity.startActivity(Activity.java:5721)
	at android.app.Activity.startActivity(Activity.java:5674)
	at com.saggitt.omega.iconpack.IconPackAdapter$DownloadHolder.onClick(IconPackAdapter.kt:259)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by machiav3lli** [comment]
This is already fixed. It just seems that you don't have a store app on your device to handle the forementioned Intent.

**Comment by 5lttrz** [comment]
@machiav3lli where does it try to get the packs from by default? Can it be configured to get packs from Aurora Store or cliets of F-Droid?

**Comment by 5lttrz** [comment]
@machiav3lli where does it try to get the packs from by default? Can it be configured to get packs from Aurora Store or cliets of F-Droid?

**Comment by machiav3lli** [comment]
It usually asks for a store link. The apps (e.g. Aurora Store) have to define a receiver for such intent. So it should implemented on their side
