### ISSUE TITLE
Crashing when creating a folder on home screen

### ISSUE THREAD

**Issue by sakulzz** [otakuhqz/Omega#150]
Hello recently I wanted to create a folder on the home screen in OmegaLauncher, suddendly the Launcher has crashed. I tried it again but always with the same result: OmegaLauncher Crashed

## Expected Behavior
Normal folder creation

## Actual Behavior
Launcher crashing

Error Code l:
Build version: 0.8.1 
Build date: 1981-01-01 01:01:02 
Current date: 2022-02-08 10:36:14 
Device: Realme RMX2075 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.UnsupportedOperationException: Final position of the spring cannot be less than the min value.
	at androidx.dynamicanimation.animation.SpringAnimation.sanityCheck(SpringAnimation.java:206)
	at androidx.dynamicanimation.animation.SpringAnimation.start(SpringAnimation.java:134)
	at androidx.dynamicanimation.animation.SpringAnimation.animateToFinalPosition(SpringAnimation.java:159)
	at com.android.launcher3.dragndrop.DragView$SpringFloatValue.animateToPos(DragView.java:596)
	at com.android.launcher3.dragndrop.DragView.move(DragView.java:507)
	at com.android.launcher3.dragndrop.DragController.handleMoveEvent(DragController.java:446)
	at com.android.launcher3.dragndrop.DragController.onDriverDragMove(DragController.java:377)
	at com.android.launcher3.dragndrop.DragDriver$InternalDragDriver.onTouchEvent(DragDriver.java:182)
	at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(DragController.java:435)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:285)
	at android.view.View.dispatchTouchEvent(View.java:14481)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3132)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2800)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:320)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:227)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3138)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3138)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3138)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3138)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:573)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1891)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4207)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:1850)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:523)
	at android.view.View.dispatchPointerEvent(View.java:14740)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6604)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6384)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5814)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5878)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5837)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6023)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5845)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6080)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5818)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5878)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5837)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5845)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5818)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8724)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8675)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8635)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8858)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:221)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:201)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8804)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8897)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1129)
	at android.view.Choreographer.doCallbacks(Choreographer.java:951)
	at android.view.Choreographer.doFrame(Choreographer.java:869)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1114)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:254)
	at android.app.ActivityThread.main(ActivityThread.java:8239)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by otakuhqz** [comment]
already fixed on v0.9.0
