### ISSUE TITLE
Crash on start v0.5.0 (build 40)

### ISSUE THREAD

**Issue by bushrang3r** [otakuhqz/Omega#16]
Possibly the same crash as previous version > #12 

New logs:

`Build version: 0.5.0 
Current date: 2020-09-30 23:17:32 
Device: LGE LG-H870 
 
Stack trace:  
java.lang.IllegalArgumentException: column 'customIcon' does not exist. Available columns: [_id, title, intent, container, screen, cellX, cellY, spanX, spanY, itemType, appWidgetId, iconPackage, iconResource, icon, appWidgetProvider, modified, restored, profileId, rank, options]
	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:352)
	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
	at com.android.launcher3.model.LoaderCursor.<init>(LoaderCursor.java:109)
	at com.android.launcher3.model.LoaderTask.loadWorkspace(LoaderTask.java:295)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:175)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
`

**Comment by otakuhqz** [comment]
It looks like you are migrating from a previous version.
Go to device settings, and clean the app data.

**Comment by bushrang3r** [comment]
Ok! Thanks!
The app works now😁👍
