### ISSUE TITLE
Crashed just after opening it.

### ISSUE THREAD

**Issue by nihalanand697** [otakuhqz/Omega#2]
Here are the logs :
Build version: 0.1.0 
Current date: 2020-07-10 23:34:20 
Device: Xiaomi Redmi Note 7 
 
Stack trace:  
java.lang.NoSuchMethodError: No static method setUncaughtExceptionPreHandler(Ljava/lang/Thread$UncaughtExceptionHandler;)V in class Ljava/lang/Thread; or its super classes (declaration of 'java.lang.Thread' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at com.android.systemui.shared.plugins.PluginManagerImpl.<init>(PluginManagerImpl.java:105)
	at com.android.systemui.shared.plugins.PluginManagerImpl.<init>(PluginManagerImpl.java:87)
	at com.android.launcher3.uioverrides.plugins.PluginManagerWrapper.<init>(PluginManagerWrapper.java:43)
	at com.android.launcher3.uioverrides.plugins.PluginManagerWrapper.lambda$BPQstKVZHu0UxNfm4Ke1dhRqRVc(Unknown Source:2)
	at com.android.launcher3.uioverrides.plugins.-$$Lambda$PluginManagerWrapper$BPQstKVZHu0UxNfm4Ke1dhRqRVc.get(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:44)
	at com.android.launcher3.widget.custom.CustomWidgetManager.<init>(CustomWidgetManager.java:72)
	at com.android.launcher3.widget.custom.CustomWidgetManager.lambda$4PlWoL7Fi3UYDeS5Huk5ETx7Hqs(Unknown Source:2)
	at com.android.launcher3.widget.custom.-$$Lambda$CustomWidgetManager$4PlWoL7Fi3UYDeS5Huk5ETx7Hqs.get(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:44)
	at com.android.launcher3.LauncherAppState.setLauncher(LauncherAppState.java:172)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:322)
	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.java:48)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by otakuhqz** [comment]
it looks like you are using Android 10. Al already fix that crash and will post a new release in one or two days.

**Comment by nihalanand697** [comment]
Yep its Q. Good to know its fixed :D

**Comment by nihalanand697** [comment]
Hey there,
I tried your latest build from telegram and it seems crashing issue is still there.
Here are the logs :
Build version: 0.2.0 
Current date: 2020-07-14 02:57:34 
Device: Xiaomi Redmi Note 7 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saggitt.omega/com.saggitt.omega.OmegaLauncher}: android.view.InflateException: Binary XML file line #46 in com.saggitt.omega:layout/launcher: Binary XML file line #17 in com.saggitt.omega:layout/overview_panel: Error inflating class com.android.quickstep.views.LauncherRecentsView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: android.view.InflateException: Binary XML file line #46 in com.saggitt.omega:layout/launcher: Binary XML file line #17 in com.saggitt.omega:layout/overview_panel: Error inflating class com.android.quickstep.views.LauncherRecentsView
Caused by: android.view.InflateException: Binary XML file line #17 in com.saggitt.omega:layout/overview_panel: Error inflating class com.android.quickstep.views.LauncherRecentsView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1233)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:341)
	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.java:58)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NoSuchMethodError: No static method getWindowCornerRadius(Landroid/content/res/Resources;)F in class Lcom/android/internal/policy/ScreenDecorationsUtils; or its super classes (declaration of 'com.android.internal.policy.ScreenDecorationsUtils' appears in /system/framework/framework.jar!classes3.dex)
	at com.android.systemui.shared.system.QuickStepContract.getWindowCornerRadius(QuickStepContract.java:205)
	at com.android.quickstep.util.ClipAnimationHelper.<init>(ClipAnimationHelper.java:106)
	at com.android.quickstep.views.RecentsView.<init>(RecentsView.java:329)
	at com.android.quickstep.views.LauncherRecentsView.<init>(LauncherRecentsView.java:97)
	at com.android.quickstep.views.LauncherRecentsView.<init>(LauncherRecentsView.java:93)
	... 29 more

**Comment by otakuhqz** [comment]
fixed in commit [1e575cce3bafb4cf7def6aa49af6ad11ed6c66b0](https://github.com/otakuhqz/Omega/commit/1e575cce3bafb4cf7def6aa49af6ad11ed6c66b0)

The version v0.2.0 (Build 6) is available in the telegram channel for testing.

**Comment by nihalanand697** [comment]
> fixed in commit [1e575cce3bafb4cf7def6aa49af6ad11ed6c66b0](https://github.com/otakuhqz/Omega/commit/1e575cce3bafb4cf7def6aa49af6ad11ed6c66b0)
> 
> The version v0.2.0 (Build 6) is available in the telegram channel for testing.

Yep just saw the build and tried, doesnt crash now. Thanks!
A question btw, does omega have its own recents provider?
