### ISSUE TITLE
The application closed on its own when trying to add an icon.

### ISSUE THREAD

**Issue by Wjxfi** [otakuhqz/Omega#335]
`FATAL EXCEPTION: main
Process: com.saggitt.omega, PID: 16908
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.ShortcutAndWidgetContainer.measureChild(android.view.View)' on a null object reference
	at com.android.launcher3.dragndrop.DragLayer.animateViewIntoPosition(DragLayer.java:241)
	at com.android.launcher3.dragndrop.DragLayer.animateViewIntoPosition(DragLayer.java:233)
	at com.android.launcher3.Workspace.onDropExternal(Workspace.java:2654)
	at com.android.launcher3.Workspace.onDrop(Workspace.java:1824)
	at com.android.launcher3.dragndrop.DragController.drop(DragController.java:534)
	at com.android.launcher3.dragndrop.DragController.onDriverDragEnd(DragController.java:379)
	at com.android.launcher3.dragndrop.DragDriver$InternalDragDriver.onTouchEvent(DragDriver.java:183)
	at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(DragController.java:420)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:267)
	at android.view.View.dispatchTouchEvent(View.java:14860)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2798)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:302)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:214)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:569)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4319)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:1959)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:527)
	at android.view.View.dispatchPointerEvent(View.java:15133)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6671)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6459)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5900)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5957)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5923)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6088)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5931)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6145)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5904)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5957)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5923)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5931)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5904)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8932)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8883)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8851)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9065)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:280)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:337)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)`

**Comment by saulhdev** [comment]
It is related to #185 and it is already fixed in the current development branch.
We will keep open this ticket until the new version is published
