### ISSUE TITLE
Crashing when creating a backup

### ISSUE THREAD

**Issue by Raul1198** [otakuhqz/Omega#34]
## Description

When I try to create a backup the app crashed. Here is the crash log - 

## Expected Behavior

Backup successful without any issues

## Actual Behavior

The launcher is crashing

## Steps to Reproduce

1. Go to settings
2. Advance Settings
3. Backup
4. Create

## Device and OS

* Device: Redmi K20 Pro
* Android version: 11
* Launcher version: 0.6.2
* Rom: Resurrection Remix 

## Logcat

```
Build version: 0.6.2 
Build date: 1981-01-01 01:01:02 
Current date: 2021-01-09 13:32:12 
Device: Xiaomi Redmi K20 Pro 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:315)
	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:220)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1500)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1340)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1288)
	at com.saggitt.omega.backup.OmegaBackup$Companion.create(OmegaBackup.kt:309)
	at com.saggitt.omega.backup.NewBackupActivity$CreateBackupTask.doInBackground(NewBackupActivity.kt:178)
	at com.saggitt.omega.backup.NewBackupActivity$CreateBackupTask.doInBackground(NewBackupActivity.kt:154)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

**Comment by Surendrajat** [comment]
I'm facing the same issue when I want to do a backup.
