### ISSUE TITLE
Unable to add Clock app to desktop

### ISSUE THREAD

**Issue by mrghosti3** [otakuhqz/Omega#58]
App: com.google.android.deskclock

Build version: 0.7.1 
Current date: 2021-02-10 13:07:01 
Device: Xiaomi Mi A1

Stack trace:
```
java.lang.IllegalStateException: unwrapped AdaptiveIconDrawable for ApplicationInfo{547ddf3 com.google.android.deskclock}
	at com.saggitt.omega.icons.CustomIconProvider.assertNotAdaptiveIconDrawable(CustomIconProvider.kt:62)
	at com.saggitt.omega.icons.CustomIconProvider.getDynamicIcon(CustomIconProvider.kt:57)
	at com.saggitt.omega.iconpack.DefaultPack.getIcon(DefaultPack.kt:144)
	at com.saggitt.omega.iconpack.IconPackManager.getIcon(IconPackManager.kt:123)
	at com.saggitt.omega.icons.CustomIconProvider.getIcon(CustomIconProvider.kt:44)
	at com.android.launcher3.icons.IconCache.getFullResIcon(IconCache.java:242)
	at com.android.launcher3.Utilities.getFullDrawable(Utilities.java:578)
	at com.android.launcher3.dragndrop.DragView$2.run(DragView.java:233)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

```

**Comment by Roan-V** [comment]
Can confirm I get the same issue on a TA-1004
I have tried resetting and completely disabling the clock app to factory values, both don't seem to work either.

**Comment by mrghosti3** [comment]
Not familiar to Kotlin, but pretty sure this part causes the error. Although the stack trace points to the last curly bracket for some reason.

```
55    private fun <T> T.assertNotAdaptiveIconDrawable(info: Any?): T {
56        if (Utilities.ATLEAST_OREO && this is AdaptiveIconDrawable) {
57            error("unwrapped AdaptiveIconDrawable for ${
58                if (info is LauncherActivityInfo) info.applicationInfo else info
59            }")
60        }
61        return this
62    }
```

**Comment by mrghosti3** [comment]
I think we can close this issue as there was another one that with the same problem ( #38 ) and @otakuhqz mentioned that this had been fixed, unless this is something new.
