### ISSUE TITLE
Crash when trying to long press some icons on desktop 

### ISSUE THREAD

**Issue by sibeliusg** [otakuhqz/Omega#63]
## Description

Long pressing some icons like eBay or PayPal on the desktop lets the launcher crash. Most other icons work though.

## Expected Behavior

A drop down menu should appear and one could move the icon on the desktop or uninstall it.
## Actual Behavior

A crash with an error report

## Steps to Reproduce

1. Long Press eBay icon on desktop

## Device and OS

* Device: Xiaomi Redmi 4x
* Android version: 8.1.0
* Launcher version: 0.7.1
* Rom: Lineage for MicroG 15.1

## Log provided by Omega Launcher

```
Build version: 0.7.1 
Current date: 2021-03-07 08:55:51 
Device: Xiaomi Redmi 4X 
 
Stack trace:  
java.lang.IllegalArgumentException: path must be convex
	at android.graphics.Outline.setConvexPath(Outline.java:284)
	at android.graphics.drawable.AdaptiveIconDrawable.getOutline(AdaptiveIconDrawable.java:387)
	at android.view.ViewOutlineProvider$1.getOutline(ViewOutlineProvider.java:38)
	at android.view.View.rebuildOutline(View.java:14960)
	at android.view.View.setBackgroundBounds(View.java:19416)
	at android.view.View.drawBackground(View.java:19381)
	at android.view.View.draw(View.java:19183)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw(View.java:19195)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at com.android.launcher3.dragndrop.DragLayer.drawChild(DragLayer.java:547)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at com.android.launcher3.dragndrop.DragLayer.dispatchDraw(DragLayer.java:539)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at com.android.launcher3.LauncherRootView.dispatchDraw(LauncherRootView.java:135)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw(View.java:19195)
	at com.android.internal.policy.DecorView.draw(DecorView.java:788)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by otakuhqz** [comment]
fixed on v0.8
