### ISSUE TITLE
Crashing on backing up

### ISSUE THREAD

**Issue by thomasrich007** [otakuhqz/Omega#64]
Error log at bottom 

## Expected Behavior

Able to backup the Launcher settings.

## Actual Behavior

Not able to save launcher backup settings.

## Steps to Reproduce

1.
2.
3.
4.

## Device and OS

* Device: Sony Xperia XA2  and Huawei P40
* Android version: Android 10
* Launcher version: 0.7.1
* Rom:

## Logcat

```
Build version: 0.7.1 
Current date: 2021-03-12 10:35:23 
Device: Sony I4113 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:315)
	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:220)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1500)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1340)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1288)
	at com.saggitt.omega.backup.OmegaBackup$Companion.create(OmegaBackup.kt:309)
	at com.saggitt.omega.backup.NewBackupActivity$CreateBackupTask.doInBackground(NewBackupActivity.kt:177)
	at com.saggitt.omega.backup.NewBackupActivity$CreateBackupTask.doInBackground(NewBackupActivity.kt:153)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

```

**Comment by otakuhqz** [comment]
fixed on v0.8
