### ISSUE TITLE
Crash when clicked on Home Widget

### ISSUE THREAD

**Issue by bebetor** [otakuhqz/Omega#67]
This problem is similar to crash #35 

## Description
Clicked on Home Settings -> Home Widget and boom!

## Expected Behavior
The app should not crash and should show relevant settings

## Actual Behavior
App crashed.

## Steps to Reproduce
1.Long press on Home Screen.
2. Click on Home Settings
3. Click on Home Widget
4. Watch it crash

## Device and OS
* Device: Xiaomi MI Pad 4 plus (clover)
* Android version: 11.0.0
* Launcher version: 0.7.1
* Rom: LineageOS 18.1 (lineage_clover-userdebug 11 RQ2A.210305.006 eng.sabar.20210315.125113 test-keys)

## Logcat

Build version: 0.7.1 
Current date: 2021-04-16 23:49:30 
Device: Xiaomi MI PAD 4 
 
Stack trace:  
android.view.InflateException: Binary XML file line #90: Error inflating class com.saggitt.omega.preferences.SmartspaceProviderPreference
	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:249)
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:361)
	at com.saggitt.omega.settings.SettingsActivity$SubSettingsFragment.onCreatePreferences(SettingsActivity.java:715)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at com.saggitt.omega.settings.SettingsActivity$BaseFragment.onCreate(SettingsActivity.java:410)
	at com.saggitt.omega.settings.SettingsActivity$SubSettingsFragment.onCreate(SettingsActivity.java:662)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:242)
	... 39 more
Caused by: java.lang.IllegalStateException: No display name for provider com.saggitt.omega.smartspace.weather.SmartspacePixelBridge
	at com.saggitt.omega.smartspace.OmegaSmartspaceController$Companion.getDisplayName(OmegaSmartspaceController.kt:561)
	at com.saggitt.omega.preferences.SmartspaceProviderPreference.<init>(SmartspaceProviderPreference.kt:44)
	... 42 more

**Comment by bebetor** [comment]
Solved in new version 0.8.0 build 167. Thanx
