### ISSUE TITLE
Crash when click on "show feed"

### ISSUE THREAD

**Issue by bebetor** [otakuhqz/Omega#69]
## Description
Click on Home settings->three dots (search bar)->show feed (under incubating) and app show crash screen

## Expected Behavior
Show feed

## Actual Behavior
App crashed

## Steps to Reproduce

1. Long press on Home Screen.
2. Click on Home Settings
3. Click on the three dots in the search bar
4. Click on developer options
5. Click on "show feed" under "incubating"
6. App crash

## Device and OS

* Device: Xiasomi MI PAD 4 PLUS
* Android version: 11
* Launcher version: 0.7.1
* Rom: LineageOS 18.1 lineage_clover-userdebug 11 RQ2A.210305.006 eng.sabar.20210315.125113 test-keys

## Logcat

Build version: 0.7.1 
Current date: 2021-04-17 10:26:16 
Device: Xiaomi MI PAD 4 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saggitt.omega/com.saggitt.omega.feed.FeedWidgetsActivity}: java.lang.IllegalArgumentException: Cannot find BaseActivity in parent tree
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalArgumentException: Cannot find BaseActivity in parent tree
	at com.android.launcher3.BaseActivity.fromContext(BaseActivity.java:281)
	at com.android.launcher3.Launcher.getLauncher(Launcher.java:2610)
	at com.saggitt.omega.feed.FeedWidgetsActivity.onCreate(FeedWidgetsActivity.java:61)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	... 11 more

**Comment by otakuhqz** [comment]
The preferences under developer options > incubating are being developed and might not work. Once they work properly they are move to the correct screen.

Bugs on this screen are not revised or fixed.

Thanks

**Comment by bebetor** [comment]
Thanx @otakuhqz
