### ISSUE TITLE
Crash on Android 7.1.2

### ISSUE THREAD

**Issue by abda11ah** [otakuhqz/Omega#70]
Hi,
I just installed the current Fdroid version and tried it by clicking on the home button, it instantly crashed.
Also the app gave me the same crash when i launched it from its desktop icon.

I think this launcher was not tested on old AOSP (Android 7.1.2, April 2018)

* Device: Meizu M6 Note
* Android version: 7.1.2
* Launcher version: 0.7.1 Build 118
* Rom: AOSP Extended 4.6

## Logcat
Build version: 0.7.1 
Build date: 1979-11-30 00:00:00 
Current date: 2021-04-19 08:35:50 
Device: Meizu M6 Note 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saggitt.omega/com.saggitt.omega.OmegaLauncher}: android.view.InflateException: Binary XML file line #56: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: android.view.InflateException: Binary XML file line #56: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:964)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.LayoutInflater.parseInclude(<Xposed>)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.LayoutInflater.inflate(<Xposed>)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:347)
	at com.google.android.apps.nexuslauncher.NexusLauncherActivity.onCreate(NexusLauncherActivity.java:25)
	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.java:93)
	at android.app.Activity.performCreate(Activity.java:6738)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/TaskStackListener;
	at com.android.systemui.shared.system.ActivityManagerWrapper.getInstance(ActivityManagerWrapper.java:99)
	at com.android.quickstep.RecentsModel.<init>(RecentsModel.java:75)
	at com.android.quickstep.RecentsModel.lambda$Qm7E187uPu5w6aJQIVw5cciOIrc(RecentsModel.java)
	at com.android.quickstep.-$$Lambda$RecentsModel$Qm7E187uPu5w6aJQIVw5cciOIrc.get(lambda)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:44)
	at com.android.quickstep.views.RecentsView.<init>(RecentsView.java:327)
	at com.android.quickstep.views.LauncherRecentsView.<init>(LauncherRecentsView.java:97)
	at com.android.quickstep.views.LauncherRecentsView.<init>(LauncherRecentsView.java:93)
	... 34 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.TaskStackListener" on path: DexPathList[[zip file "/data/app/com.saggitt.omega-1/base.apk"],nativeLibraryDirectories=[/data/app/com.saggitt.omega-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 42 more

**Comment by breversa** [comment]
Same here on a Samsung Galaxy S4 Mini :

```
Build version: 0.7.1 
Current date: 2021-05-06 10:44:58 
Device: Samsung GT-I9195 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saggitt.omega/com.saggitt.omega.OmegaLauncher}: android.view.InflateException: Binary XML file line #56: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: android.view.InflateException: Binary XML file line #56: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:964)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:347)
	at com.google.android.apps.nexuslauncher.NexusLauncherActivity.onCreate(NexusLauncherActivity.java:25)
	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.java:93)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/TaskStackListener;
	at com.android.systemui.shared.system.ActivityManagerWrapper.getInstance(ActivityManagerWrapper.java:99)
	at com.android.quickstep.RecentsModel.<init>(RecentsModel.java:75)
	at com.android.quickstep.RecentsModel.lambda$Qm7E187uPu5w6aJQIVw5cciOIrc(RecentsModel.java)
	at com.android.quickstep.-$$Lambda$RecentsModel$Qm7E187uPu5w6aJQIVw5cciOIrc.get(lambda)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:44)
	at com.android.quickstep.views.RecentsView.<init>(RecentsView.java:327)
	at com.android.quickstep.views.LauncherRecentsView.<init>(LauncherRecentsView.java:97)
	at com.android.quickstep.views.LauncherRecentsView.<init>(LauncherRecentsView.java:93)
	... 27 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.TaskStackListener" on path: DexPathList[[zip file "/data/app/com.saggitt.omega-1/base.apk"],nativeLibraryDirectories=[/data/app/com.saggitt.omega-1/lib/arm, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 35 more

```

**Comment by otakuhqz** [comment]
Sorry @breversa but android 7 is not supported.

**Comment by breversa** [comment]
Thats unfortunate.
Is there a way to prevent installation on Android < 8 then ?

**Comment by otakuhqz** [comment]
Yes, it the next build will be updated the minimun SDK.
