### ISSUE TITLE
Crash after phone restart

### ISSUE THREAD

**Issue by Aviortheking** [otakuhqz/Omega#95]
Launcher crashed after phone restart

Even restarting it kept crashing

```
Build version: 0.8.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-07-11 15:15:56 
Device: OnePlus ONEPLUS A6010 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.LayerDrawable.getNumberOfLayers()' on a null object reference
	at com.google.android.apps.nexuslauncher.clock.CustomClock.getClockLayers(CustomClock.java:63)
	at com.google.android.apps.nexuslauncher.clock.CustomClock.getClock(CustomClock.java:40)
	at com.saggitt.omega.iconpack.IconPackImpl.getIcon(IconPackImpl.kt:293)
	at com.saggitt.omega.iconpack.IconPackManager.getIcon(IconPackManager.kt:130)
	at com.saggitt.omega.icons.CustomIconProvider.getIcon(CustomIconProvider.kt:44)
	at com.android.launcher3.icons.LauncherActivityCachingLogic.loadIcon(LauncherActivityCachingLogic.java:64)
	at com.android.launcher3.icons.LauncherActivityCachingLogic.loadIcon(LauncherActivityCachingLogic.java:33)
	at com.android.launcher3.icons.cache.BaseIconCache.cacheLocked(BaseIconCache.java:337)
	at com.android.launcher3.icons.IconCache.getTitleAndIcon(IconCache.java:307)
	at com.android.launcher3.icons.IconCache.getTitleAndIcon(IconCache.java:193)
	at com.android.launcher3.model.AllAppsList.add(AllAppsList.java:149)
	at com.android.launcher3.model.LoaderTask.loadAllApps(LoaderTask.java:931)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:214)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by otakuhqz** [comment]
Fixed on v0.8.1
